name: Update Snake Daily

on:
  schedule:
    - cron: "30 12 * * *"  # Update setiap hari jam 12:30 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: "irfan-efendi19"  # Ganti dengan username GitHub Anda
        id: snake-gif
      
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
