name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: "irfan-efendi19"

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: "output"
          build_dir: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
